adding inheritance from bacterium class
ingallslab/bsim pull request #11
Opened 2021-10-01 00:32 UTC by Ati-74

please review two things: 1) adding inheritance from bacterium class 2)test file modification. thanks
@cheekolegend

2021-10-04 15:56 UTC, cheekolegend requested changes
Physical contact bacterium should only have functionalities associated with physical contact. Remove variables associated with toxin fields.

2021-10-04 16:02 UTC, cheekolegend requested changes

2021-10-04 16:02 UTC, cheekolegend commented on src/bsim/winter2021/Bacterium.java
> +    public int contact;
Remove these from Bacterium.java; these should only be associated with certain types of bacteria

2021-10-04 16:02 UTC, cheekolegend commented on src/bsim/winter2021/Bacterium.java
> +        contact=0;
Remove these from Bacterium.java; these should only be associated with certain types of bacteria

2021-10-04 16:02 UTC, cheekolegend commented on src/bsim/winter2021/Bacterium.java
> +        contact=0;
Remove these from Bacterium.java; these should only be associated with certain types of bacteria

2021-10-04 16:02 UTC, cheekolegend commented on src/bsim/winter2021/Bacterium.java
> +        this.contact= 0;
Remove these from Bacterium.java; these should only be associated with certain types of bacteria

2021-10-08 13:30 UTC, Ati-74 commented
Changes associated with Bacterium.java are implemented, and the test file is updated.
@cheekolegend

2021-10-14 19:44 UTC, cheekolegend approved these changes

2021-10-14 19:47 UTC, merged